openapi: '3.0.2'
info:
  title: Addition Service for numbers
  version: '1.0'
servers:
  - url: /api/v1
paths:
  /addition:
    post: 
      description: Add two numbers
      operationId: addNumbers
      requestBody:
        description: Numbers to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description:   result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  /concat:
    post: 
      description: concat two strings
      operationId: concatStrings
      requestBody:
        description: Strings to be concatenated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Texts'
      responses:
        '200':
          description:   result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultString'      
components: 
  schemas:
    Numbers:
      description: Holds two numbers to be operated on
      required:
          - numberone
          - numbertwo
      type: object
      properties:
        numberone:
          type: number
          description: First Number
        numbertwo:
          type: number
          description: Second Number
    Texts:
      description: Holds two strings to be operated on
      required:
          - stringone
          - stringtwo
      type: object
      properties:
        stringone:
          type: string
          description: First Number
        stringtwo:
          type: string
          description: Second Number
    Result:
      description: Holds the result of the operation
      type: object
      properties:
        resultingvalue:
          type: number
          description: result
    ResultString:
      description: Holds the result of the operation
      type: object
      properties:
        resultingvalue:
          type: string
          description: result

